# Site settings
title: ICQMC 2026
description: 6th ICQMC Annual Meeting - May 15-18, 2026,  Guilin, China
url: "" # Leave empty for GitHub Pages auto-detection
baseurl: "" # Leave empty if hosting at username.github.io/

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
